export const INDUSTRY_PAGES = [
  {
    slug: 'resorts-tourism',
    title: 'Odoo ERP & Business Services for Maldives Resorts | Metamorphosis MV',
    h1: 'Odoo ERP & Business Services for Maldives Resorts',
    description: 'ERP implementation, accounting, procurement and staff management for Maldivian resort operators. Certified Odoo Silver Partner based in Malé.',
    intro: 'Metamorphosis MV provides Odoo ERP implementation, MIRA-compliant accounting, procurement support, and HR management specifically for resort and tourism businesses across the Maldives. Our team has on-the-ground experience with the operational realities of island-based resort management.',
    services: ['Odoo ERP for Resort Operations', 'MIRA-Compliant Accounting', 'Procurement & Vendor Management', 'HR & Staff Payroll', 'Guest House Management', 'Government Liaison'],
    faqs: [
      { q: 'Can Odoo ERP be used for resort management in the Maldives?', a: 'Yes. Odoo includes modules for inventory, procurement, HR, payroll, accounting, and point of sale — all relevant for resort operations. Metamorphosis MV customizes Odoo for the specific needs of Maldivian resorts, including multi-currency handling, inter-atoll logistics, and MIRA-compliant reporting.' },
      { q: 'Do you handle accounting for resort businesses under MIRA?', a: 'Yes. We provide full MIRA-compliant bookkeeping, GST filing, income tax returns, and audit-ready financial reporting for resort operators of all sizes — from boutique guesthouses to full-service resorts.' },
      { q: 'Can you manage procurement and supplier relationships for a resort?', a: 'Yes. Our procurement support service covers supplier identification, cost negotiation, purchase orders, and inter-atoll logistics coordination — reducing the operational burden on resort management teams.' },
    ],
    serviceType: 'ERP and Business Services for Resort Operations',
    keyword: 'odoo erp maldives resorts',
  },
  {
    slug: 'guesthouses',
    title: 'Accounting & Management for Maldives Guesthouses | Metamorphosis MV',
    h1: 'Accounting & Business Management for Maldives Guesthouses',
    description: 'MIRA-compliant accounting, guesthouse management, and business consulting for guesthouse operators across the Maldives. Based in Malé.',
    intro: 'Metamorphosis MV offers complete accounting, operations management, and business consulting for guesthouse owners across the Maldives. Whether you operate in Malé or across the atolls, we handle your MIRA filings, daily bookkeeping, staff management, and supplier coordination.',
    services: ['Guest House Management', 'MIRA Accounting & GST Filing', 'Payroll & Staff Management', 'Procurement Support', 'Business Consulting', 'Company Registration'],
    faqs: [
      { q: 'Do guesthouses in Maldives need to file GST with MIRA?', a: 'Yes. Guesthouses registered for GST in the Maldives must file monthly or annual GST returns with MIRA. Metamorphosis MV handles GST registration, monthly returns, and income tax filings for guesthouse operators across the atolls.' },
      { q: 'Can you manage daily operations of a guesthouse?', a: 'Yes. Our guest house management service covers front-desk operations, staff scheduling, supplier coordination, and financial reporting — allowing owners to focus on guests rather than administration.' },
      { q: 'Do you work with guesthouses outside Malé?', a: 'Yes. We work with guesthouse operators across the Maldives atolls. Our services are delivered remotely or on-site depending on the engagement type.' },
    ],
    serviceType: 'Guesthouse Management and Accounting',
    keyword: 'guesthouse management accounting maldives',
  },
  {
    slug: 'trading-companies',
    title: 'MIRA Accounting for Trading Companies in Maldives | Metamorphosis MV',
    h1: 'MIRA-Compliant Accounting for Trading Companies in Maldives',
    description: 'GST filing, income tax, bookkeeping and Odoo ERP for import-export and trading companies in the Maldives. Certified specialists based in Malé.',
    intro: 'Metamorphosis MV provides MIRA-compliant accounting, Odoo ERP implementation, and business consulting for trading and import-export companies operating in the Maldives. We handle GST, income tax, inventory management, and procurement — keeping your operations compliant and efficient.',
    services: ['MIRA Accounting & GST Filing', 'Odoo Inventory Management', 'Procurement Support', 'Income Tax Returns', 'Business Consulting', 'Financial Reporting'],
    faqs: [
      { q: 'What MIRA taxes apply to trading companies in the Maldives?', a: 'Trading companies in the Maldives are typically subject to GST (Goods and Services Tax) at 8% and Business Profit Tax (BPT) under income tax regulations. Metamorphosis MV handles both GST returns and income tax filings to keep your business fully MIRA-compliant.' },
      { q: 'Can you manage inventory and procurement in Odoo for a trading company?', a: 'Yes. Odoo\'s inventory and purchase modules are ideal for trading companies — tracking stock levels, managing supplier orders, and integrating directly with accounting. We implement and customize Odoo for the specific needs of Maldivian traders.' },
    ],
    serviceType: 'Accounting and ERP for Trading Companies',
    keyword: 'mira accounting trading company maldives',
  },
  {
    slug: 'construction',
    title: 'Business Consulting for Construction Companies in Maldives | Metamorphosis MV',
    h1: 'Business Consulting & ERP for Construction Companies in Maldives',
    description: 'Project management, accounting, procurement and Odoo ERP for construction and contracting companies in the Maldives. Malé-based specialists.',
    intro: 'Metamorphosis MV supports construction and contracting companies across the Maldives with project management, MIRA-compliant accounting, procurement coordination, and Odoo ERP implementation. We understand the logistical challenges of inter-atoll construction projects.',
    services: ['Project Management', 'MIRA Accounting', 'Procurement & Supplier Management', 'Odoo ERP (Project + Purchase)', 'HR & Labour Management', 'Company Registration'],
    faqs: [
      { q: 'Can Odoo manage construction project costs and timelines?', a: 'Yes. Odoo\'s Project and Purchase modules allow construction companies to track project budgets, labour costs, material procurement, and timelines in one system. Metamorphosis MV configures Odoo specifically for construction project management.' },
      { q: 'Do you handle accounting and tax for construction companies in Maldives?', a: 'Yes. Construction companies in the Maldives are subject to GST and BPT. We handle all MIRA filings, project-based bookkeeping, and payroll for construction firms operating across the atolls.' },
    ],
    serviceType: 'Business Consulting and ERP for Construction',
    keyword: 'business consulting construction maldives',
  },
  {
    slug: 'expats',
    title: 'Work Permit & Expat Services in Maldives | Metamorphosis MV',
    h1: 'Work Permit (DVR) & Expat Services in the Maldives',
    description: 'DVR work permit processing, dependent visas, expat relocation and government liaison for expatriates working in the Maldives. Fast, compliant, end-to-end service from Malé.',
    intro: 'Metamorphosis MV provides end-to-end expatriate services for foreign nationals working in the Maldives — from DVR work permit applications and dependent visas to housing support, banking setup, and Ministry of Economic Development liaison. We handle the paperwork so you can focus on your work.',
    services: ['DVR Work Permit Processing', 'Dependent Visa', 'Expat Relocation Support', 'Government Liaison', 'Company Registration', 'Compliance Advisory'],
    faqs: [
      { q: 'What is a DVR and who needs one to work in the Maldives?', a: 'A DVR (Diversity Visa Registration) is required for all foreign nationals employed in the Maldives. Employers must obtain a DVR quota from the Ministry of Economic Development before hiring expatriate workers. Metamorphosis MV manages the full DVR application and renewal process.' },
      { q: 'How long does a work permit take in the Maldives?', a: 'Standard DVR processing in the Maldives takes 2–4 weeks depending on quota availability and documentation completeness. Metamorphosis MV prepares all documentation and liaises directly with MED to ensure the fastest possible processing time.' },
      { q: 'Can you help with housing and banking for expats arriving in Malé?', a: 'Yes. Our expat relocation service covers housing search in Malé, bank account setup, school enrollment for dependents, and practical onboarding — making the transition to life in the Maldives as smooth as possible.' },
    ],
    serviceType: 'Expat and Immigration Services',
    keyword: 'expat services work permit maldives',
  },
];

export const COMPARE_PAGES = [
  {
    slug: 'odoo-vs-quickbooks-maldives',
    title: 'Odoo vs QuickBooks for Maldivian Businesses | Metamorphosis MV',
    h1: 'Odoo vs QuickBooks: Which is Better for Maldivian Businesses?',
    description: 'Comparing Odoo and QuickBooks for businesses in the Maldives. MIRA compliance, multi-module integration, local support. Which ERP wins for Maldivian SMEs?',
    intro: 'Choosing between Odoo and QuickBooks is one of the most common decisions for growing Maldivian businesses. Both handle accounting, but they differ significantly in scope, MIRA compliance capabilities, and local support availability.',
    winner: 'Odoo',
    winnerReason: 'Odoo covers accounting, inventory, HR, CRM, and operations in one platform — essential for Maldivian businesses that need multi-module integration. QuickBooks is accounting-only and has no local Maldives support.',
    comparison: [
      { feature: 'MIRA GST Filing', odoo: '✓ Configurable for Maldives tax', other: '✗ No Maldives localisation' },
      { feature: 'Inventory Management', odoo: '✓ Full module included', other: '✗ Add-on only' },
      { feature: 'HR & Payroll', odoo: '✓ Full module included', other: '✗ Not included' },
      { feature: 'Local Support in Maldives', odoo: '✓ Metamorphosis MV', other: '✗ No local partner' },
      { feature: 'Multi-currency', odoo: '✓ Built-in', other: '✓ Available' },
      { feature: 'Open Source', odoo: '✓ Community edition free', other: '✗ Subscription only' },
    ],
    otherName: 'QuickBooks',
    keyword: 'odoo vs quickbooks maldives',
  },
  {
    slug: 'odoo-vs-sage-maldives',
    title: 'Odoo vs Sage for Businesses in Maldives | Metamorphosis MV',
    h1: 'Odoo vs Sage: Which is Better for Businesses in Maldives?',
    description: 'Comparing Odoo and Sage ERP for Maldivian businesses. Local support, MIRA compliance, scalability. Expert comparison from certified Odoo partner in Malé.',
    intro: 'Sage and Odoo are both popular ERP and accounting platforms, but for Maldivian businesses, the choice often comes down to local support, MIRA compliance, and the ability to scale beyond basic accounting.',
    winner: 'Odoo',
    winnerReason: 'Odoo offers broader functionality, open-source flexibility, and has a certified local partner (Metamorphosis MV) in Malé. Sage has no local Maldives support and limited integration with Maldivian government systems.',
    comparison: [
      { feature: 'MIRA GST Compliance', odoo: '✓ Configurable for Maldives', other: '⚠ Requires customisation' },
      { feature: 'Local Partner in Maldives', odoo: '✓ Metamorphosis MV (Silver Partner)', other: '✗ No local partner' },
      { feature: 'Manufacturing Module', odoo: '✓ Full module', other: '✓ Available in higher tiers' },
      { feature: 'Open Source Option', odoo: '✓ Community edition', other: '✗ Proprietary only' },
      { feature: 'CRM Integration', odoo: '✓ Native', other: '✓ Available' },
      { feature: 'Mobile App', odoo: '✓ iOS & Android', other: '✓ Available' },
    ],
    otherName: 'Sage',
    keyword: 'odoo vs sage maldives',
  },
  {
    slug: 'best-accounting-software-maldives',
    title: 'Best Accounting Software for Maldivian Businesses 2026 | Metamorphosis MV',
    h1: 'Best Accounting Software for Maldivian Businesses in 2026',
    description: 'Expert comparison of the best accounting software for businesses in Maldives. MIRA compliance, GST filing, local support. Odoo, QuickBooks, Sage, Xero compared.',
    intro: 'Selecting accounting software for a Maldivian business requires considering MIRA compliance, GST filing capabilities, multi-currency support, and whether you can get local support in Malé when issues arise. Here is our expert comparison of the most common options.',
    winner: 'Odoo',
    winnerReason: 'For Maldivian businesses, Odoo is the strongest choice — it can be configured for MIRA GST and income tax, integrates with inventory and HR, and has a certified local implementation partner in Malé (Metamorphosis MV).',
    comparison: [
      { feature: 'MIRA GST Filing', odoo: '✓ Configurable', other: 'Varies by platform' },
      { feature: 'Local Support in Malé', odoo: '✓ Certified partner', other: '✗ Remote only' },
      { feature: 'Full ERP (beyond accounting)', odoo: '✓ Yes', other: '✗ Most are accounting-only' },
      { feature: 'Free Tier', odoo: '✓ Community edition', other: '✗ Subscription required' },
      { feature: 'Multi-currency', odoo: '✓ Built-in', other: 'Varies' },
      { feature: 'Mobile Access', odoo: '✓ iOS & Android', other: 'Varies' },
    ],
    otherName: 'QuickBooks / Sage / Xero',
    keyword: 'best accounting software maldives',
  },
  {
    slug: 'best-erp-maldives',
    title: 'Best ERP Software for Businesses in Maldives 2026 | Metamorphosis MV',
    h1: 'Best ERP Software for Businesses in the Maldives in 2026',
    description: 'Expert guide to the best ERP software for Maldivian businesses. Odoo, SAP, Microsoft Dynamics compared for MIRA compliance, local support, and cost. From a certified Odoo Silver Partner in Malé.',
    intro: 'Enterprise Resource Planning (ERP) software helps Maldivian businesses manage accounting, inventory, HR, procurement, and operations in one integrated system. Choosing the right ERP depends on your business size, budget, and whether local implementation support is available.',
    winner: 'Odoo',
    winnerReason: 'For Maldivian SMEs, Odoo is the clear winner — it is comprehensive, affordable, open-source, and has a certified Silver Partner (Metamorphosis MV) offering local implementation and support in Malé.',
    comparison: [
      { feature: 'Suitable for SMEs', odoo: '✓ Yes', other: '⚠ SAP/Dynamics are enterprise-focused' },
      { feature: 'Local Partner in Maldives', odoo: '✓ Metamorphosis MV', other: '✗ None known' },
      { feature: 'MIRA Compliance', odoo: '✓ Configurable', other: '⚠ Requires expensive customisation' },
      { feature: 'Implementation Cost', odoo: '✓ Affordable', other: '✗ High (SAP/Dynamics)' },
      { feature: 'Open Source', odoo: '✓ Community edition', other: '✗ Proprietary' },
      { feature: 'Modules Available', odoo: '✓ 30+ modules', other: '✓ Comparable' },
    ],
    otherName: 'SAP / Microsoft Dynamics',
    keyword: 'best erp maldives',
  },
];

export const LOCATION_PAGES = [
  {
    slug: 'male',
    title: 'Business Services in Malé, Maldives | Metamorphosis MV',
    h1: 'Business Services in Malé, Maldives',
    description: 'Odoo ERP, MIRA accounting, business consulting, app development and expat visa services in Malé, Maldives. Headquartered locally for fast response.',
    intro: 'Metamorphosis MV is headquartered in Malé, Maldives — providing Odoo ERP implementation, MIRA-compliant accounting, business consulting, app development, and expat visa services to local businesses. Being Malé-based means faster response times, on-site meetings, and direct government liaison on your behalf.',
    location: 'Malé',
    keyword: 'business services male maldives',
  },
  {
    slug: 'atolls',
    title: 'Business & Accounting Services Across Maldives Atolls | Metamorphosis MV',
    h1: 'Business & Accounting Services Across Maldives Atolls',
    description: 'Odoo ERP, MIRA accounting, guesthouse management and expat services across Maldives atolls. Remote and on-site service from Malé-based specialists.',
    intro: 'Metamorphosis MV serves businesses across all Maldives atolls — not just Malé. Our accounting, ERP, and consulting services are delivered remotely or with on-site visits depending on your needs. Guesthouse operators, resort businesses, and atoll-based trading companies all benefit from our Maldives-wide coverage.',
    location: 'Maldives Atolls',
    keyword: 'business services atolls maldives',
  },
  {
    slug: 'resorts',
    title: 'ERP & Business Services for Maldives Resort Operations | Metamorphosis MV',
    h1: 'ERP & Business Services for Maldives Resort Operations',
    description: 'Odoo ERP implementation, accounting, procurement and staff management for resort operators across the Maldives. Certified Odoo Silver Partner in Malé.',
    intro: 'Metamorphosis MV specialises in business services for Maldives resort operators — implementing Odoo ERP for operations management, handling MIRA-compliant accounting, coordinating procurement, and managing expatriate work permits. Our team understands the unique challenges of running a resort business across the atolls.',
    location: 'Maldives Resorts',
    keyword: 'resort business services maldives',
  },
];
